---
development:
  cloud_name: dr6unbe9x
  api_key: '971838158668775'
  api_secret: yn3ReXmRrOUAfRhVUDD1PaEUbwo
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dr6unbe9x
  api_key: '971838158668775'
  api_secret: yn3ReXmRrOUAfRhVUDD1PaEUbwo
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dr6unbe9x
  api_key: '971838158668775'
  api_secret: yn3ReXmRrOUAfRhVUDD1PaEUbwo
  enhance_image_tag: true
  static_file_support: false
